name: Code Checks

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    code_checks:
        strategy:
            matrix:
                actions:
                    -
                        name: 'PHPStan'
                        run: vendor/bin/phpstan analyse --configuration=.github/config/phpstan.neon --ansi --error-format symplify --memory-limit 1G

                    -
                        name: 'Coding Standard'
                        run: composer check-cs

                    -
                        name: 'Rector'
                        run: vendor/bin/rector process --dry-run --ansi

                    -
                        name: 'Commented PHP Code'
                        run: vendor/bin/easy-ci check-commented-code src tests --line-limit 3

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    extensions: pdo_sqlite, pdo_mysql, pdo_pgsql
                    coverage: none
                    tools: phpunit:11.3

            -   run: composer install --no-progress

            -   run: ${{ matrix.actions.run }}
